### PR TITLE
Made the examples cross platform compatible

### LINKED ISSUE #91: (sdl2-examples:basic-test) crashes with 'NSInternalInconsistencyException'
My system:
- macOS Sierra 10.12.15
- cl-sdl2 version: cl-sdl2-20170516-git
- SDL2 version 2.0.5
- sbcl 1.3.17

When I run

    (ql:quickload :sdl2)
    (asdf:load-system :sdl2/examples)
    (sdl2-examples:basic-test)

I get this nasty error:

    Using SDL Library Version: 2.0.4
    Setting up window/gl.
    Opening game controllers.
    Beginning main loop.
    2017-06-09 20:56:28.827 sbcl[1504:99014] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
    *** First throw call stack:
    (
    	0   CoreFoundation                      0x00007fffb8bc957b __exceptionPreprocess + 171
    	1   libobjc.A.dylib                     0x00007fffcde0d1da objc_exception_throw + 48
    	2   AppKit                              0x00007fffb6db5e82 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4480
    	3   SDL2                                0x0000000000452a5a SDL2 + 244314
    	4   SDL2                                0x000000000043e39d SDL2 + 160669
    	5   ???                                 0x0000000022b8f0ee 0x0 + 582545646
    	6   ???                                 0x0000000022bd9b89 0x0 + 582851465
    	7   ???                                 0x0000000022bd9606 0x0 + 582850054
    	8   ???                                 0x0000000022bb07c6 0x0 + 582682566
    	9   ???                                 0x0000000022bb11a9 0x0 + 582685097
    	10  ???                                 0x00000000229c2640 0x0 + 580658752
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException
    fatal error encountered in SBCL pid 1504(tid 0xb0000000):
    SIGABRT received.

### PR DESCRIPTION
**Pull request by tavurth**
Fixes #91

### CODE REVIEW

**Comment by rpav** [comment]
This is not to my knowledge necessary for anything but SBCL on OSX, and even then it's unclear if it works in recent revisions.  Doing this (`make-this-thread-main`) requires special handling and is problematic in the common case.  It should be documented, but not as the primary method for initialization.

**Comment by tavurth** [comment]
Perhaps we can change the readme to show the solution for OSX users?

When I originally came across cl-sdl2 I rejected it as it didn't work on my platform. It'd be a shame to see others fall foul of the same issue, when it seems like a well thought out wrapper.

**Comment by rpav** [comment]
I don't disagree and if you want to add/maintain a section on OSX stuff that'd be great.  Part of the problem is every OSX revision seems to break this somehow, but the other part of the problem is there's really no maintainer with dedicated knowledge/hardware/etc to tweak and fix it.

**Comment by tavurth** [comment]
Sure, I've updated the readme with some OSX specifics.
I'm writing a multithreaded system based on cl-sdl2 OSX & SBCL now, so if I come across any issues I'll submit bug reports, and perhaps take a stab at fixing them.

I've changed (ASDF:load-system) to (ql:quickload) as it seems to more popular these days. I can revert if you'd prefer.

**Comment by rpav** [comment]
Thanks!

**Pull request merged**
