### PR TITLE
Add *thread-return-channel* for in-main-thread.

### PR DESCRIPTION
**Pull request by npatrick04**
I found a program that almost always consistently worked in
windows...and then just stopped for no apparent reason.  The same exact
program would run just fine on Linux.  So I tried CCL instead of
SBCL...and found the same thing.  So I'm guessing that there is some
race condition going on with respect to the way the Windows threading
model is different from Linux that has to do with how the in-main-thread
macro generated a new channel for each use.

I don't quite understand the rationale for the separate main thread that is then serialized with channels.  Regardless, this change resolved my issues on Windows with no obvious adverse affects.

### CODE REVIEW

**Comment by rpav** [comment]
This won't work, or at least, will work for precisely 1 thread lucky enough to exclusively call the main channel and get a return.  If you're only executing one thing, this will probably appear to work fine.  However in the general case it will not.

The need for specific return channels is because when listening on a channel, only one (random) thread *receives* a message.  If there is only one thread, it gets the message.  Multiple threads can of course send.

Perhaps mutexes or conditions work differently on Windows?  Can you isolate exactly what part is stopping?  I.e., before the call, after the return, which thread, etc.

**Comment by rpav** [comment]
It's possible `trivial-timeout` has issues in Windows as well, even with a `nil` timeout, which is all cl-sdl2 uses.

**Comment by npatrick04** [comment]
It is blocking on the timeout when I break.  Looking at trivial timeout...I've got some doubts.  

I see what you mean about only being able to send commands from one thread.  That does seem like the most likely situation.  If you use with-init, you can never send more commands until you get a return.  I'll do a bit more tinkering.

**Comment by rpav** [comment]
I've updated trivial-channels to not use trivial-timeouts unless there's an actual timeout.  Does this fix your issue?

**Comment by npatrick04** [comment]
The timeout was not the issue.  I've done some looking into it and found that the back-and-forth message passing was just masking the issue due to my not understanding the threading behavior.

It now appears to be just failing to present.  The idle handler is running repeatedly without a window showing.

**Pull request closed without merging**
