### PR TITLE
Fixed OSX threading issues

### PR DESCRIPTION
**Pull request by tavurth**
Since the threading issues on OSX were causing me some more grief, this pull request fixes the issues of `nextEventMatchingMask` being called outside the main thread.

## Tested
- SBCL & CCL on OSX
- `(basic-test)` --> 
  - SBCL: working by default, I've removed that section from the readme.
  - CCL: working (functions better than before, as we had some bugs while quitting)

## Brief
I switched to using [`:trivial-main-thread`](https://github.com/Shinmera/trivial-main-thread), as it handles the calling in main thread considerations far more completely than we currently can without adding a lot of extra code.

Removed the `cl-glut` dependancy on OSX, creating a window now functions correctly without this.

## Fixes:
- https://github.com/lispgames/cl-sdl2/issues/29
- https://github.com/lispgames/cl-sdl2/issues/91

## Naming convention changes
- No functionality changes. 
- One function (make-this-thread-main) is now marked as depreciated.

Please let me know if you see any issues, I'll help to resolve them.

### CODE REVIEW

**Comment by rpav** [comment]
Cool; however this changes a lot and will require some compatibility testing with at least the existing examples/code for this/`sdl2kit`/`glkit`.  And notably on Window/Linux as well, since each have their own threading requirements.

Also (at a glance) it appears to reverse the behavior for `:background` in `with-event-loop`, since `:background` and `:blocking` should be mutually inverse.

**Comment by tavurth** [comment]
Hmm, you could be right. I'll take a look at it when I get home later this evening.

I can test on Linux and Mac, and perhaps Windows tomorrow. I'll post the results here.

**Comment by tavurth** [comment]
[I wrote a quick test suite](https://gist.github.com/tavurth/28201fc710a068852f6467fca15e0f4f)

### OSX stats:
 Lisp | Current Passing | TMT Passing
 ---- | ---- | ---- |
SBCL | 3 | 4
CCL | 3 | 3

The examples which passed where all of the `cl-sdl2` examples. Although I was unable to include `cairo-test` in these results as it's not included in the `sdl2-examples` package. I tried it separately in CCL and SBCL, it's working well in both.

The SDL2kit tests failed completely on the older version of `cl-sdl2`, and on the newer version they created a while window which could be closed.

Maybe it's because of my Mac, It really doesn't play well with the examples in `glkit` or `sdl2kit`.
I have a 2015 Macbook air, running OSX 10.12.6.

None of the `glkit` tests ran on my system, giving no error and just an empty terminal after the function call. 

Perhaps there's something amiss with my tests? I'll check on Ubuntu tomorrow.

**Comment by tavurth** [comment]
### Ubuntu stats:
 Lisp | Current Passing | TMT Passing | Total tests
 ---- | ---- | ---- | ---- |
SBCL | 3 | 3 | 11
CCL | 3 | 3 | 11

This seems really similar to the above mac results. 

Tests using current `cl-sdl2` and with TMT were very similar. CCL on Linux managed to get three of the VAO windows opened, but then they greyed out and froze over (Both versions).

At the moment, the only tests which function well across all platforms are the `cl-sdl2` tests.

**Comment by tavurth** [comment]
CL-SDL2 seems to be fairly robust after the changes, running cross-platform without extra pre-processing or language specific options in the main library itself.

I can't commit to supporting SDL2Kit or GLKit, as I won't be using them for my project.

**Comment by rpav** [comment]
Cool, I'll try and take a look at this today.

**Comment by tavurth** [comment]
- I changed the naming of `blocking` back to `background` as it was before.
- I added the cairo2 test to the `cl-sdl2` examples package

**Comment by tavurth** [comment]
Any updates on if we can yet merge this to the base branch?

**Pull request closed without merging**
