### PR TITLE
Add set-texture-blend-mode and set-render-draw-blend-mode functions

### PR DESCRIPTION
**Pull request by taptap**

### CODE REVIEW

**Comment by rpav** [comment]
Thanks!

**Comment by JeremyCooper** [comment]
What do I pass as the "blend-mode"? 'SDL_BLENDMODE_ADD does not seem to be valid.

**Comment by JeremyCooper** [comment]
Alright, found that I should pass it :sdl-blendmode-add however
`(sdl2:set-render-draw-blend-mode renderer :sdl-blendmode-add)`
still returns nil causing an error. Any ideas?

**Comment by rpav** [comment]
Actually you should probably pass it `:none`, `:blend:`, `:add`, or `:mod`, but that's just a guess.  Additionally, I'm not sure how this is returning `NIL` .. it should be returning 0 or signalling an error.  Do you have a gist of your code?

**Comment by JeremyCooper** [comment]
Passing it :add ended up doing the trick. Funny though, because slime recognized :sdl-blendmode-add, sdl-bendmode-none, etc. Is there any documentation on the API differences from sdl2 to cl-sdl2?

**Comment by rpav** [comment]
Sadly not.  This should (and could easily) be generated by autowrap, but I haven't/don't really have the time to add it.  In general though, common prefixes are removed.  However I think full symbols are also retained for looking up constants by full name, or something similar.

**Comment by JeremyCooper** [comment]
Gotcha. Once I get a bit more of a handle on things and if I keep using this wrapper I might try and help out. Thanks for helping me out!

**Pull request merged**
