### PR TITLE
Add render draw functions

### PR DESCRIPTION
**Pull request by agentultra**
Add basic primitive drawing functions.

### CODE REVIEW

**Comment by agentultra** [comment]
I'd like to consider merging this now. I'm still not 100% happy with the implementation but I'd like to follow up with @rpav in another PR to address it.

**Comment by rpav** [comment]
I think my only quibble here is that it would be more useful for the "plural" functions to take lists-of or vectors-of rather than `&rest` simply because in non-demo code that's what you'll primarily be passing, rather than hard-coding points.  Of course, one could use `APPLY`, but it seems preferable not to require that for the "common case".  

Instead something like:

```lisp
(render-draw-points R POINTS)
(render-draw-points* R &rest POINTS)
```

Otherwise this looks good.

**Comment by agentultra** [comment]
I might've mucked up this branch a bit. I can create a new PR if necessary. Can I get a review before proceeding?

Cheers

**Comment by rpav** [comment]
Sorry for the delay, this looks good to me!  The conflict is probably the recent addition i did to `keyboard.lisp`.

**Comment by agentultra** [comment]
You may have to merge and fix the conflicts. Apologies.

**Comment by rpav** [comment]
Oh crap, I thought I had done this and apparently it fell off my plate.  Sorry!  Merged!

**Pull request merged**
